apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-kotlin-deployment
  labels:
    app: rest-kotlin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-kotlin
  template:
    metadata:
      labels:
        app: rest-kotlin
    spec:
      containers:
        - name: rest-kotlin
          image: pedrofraca/rest-kotlin-quickstart:e673565
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: rest-kotlin-service
spec:
  selector:
    app: rest-kotlin
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080